---

- name: Install packages
  yum: name={{ item }} state=installed
  with_items:
    - MySQL-python
    - libselinux-python
    - mysql-libs
    - mysql-connector-java

- name: Install WGET
  yum: name=wget state=installed

- name: Download lib
  get_url: url=https://dev.mysql.com/get/mysql57-community-release-el7-9.noarch.rpm dest=/usr/mysql/mysql57-community-release-el7-9.noarch.rpm

- name: Install rpm
  yum: name=/usr/mysql/mysql57-community-release-el7-9.noarch.rpm state=present

- name: Install mySQL
  yum: name=mysql-server state=installed

- name: ensure mysql started
  service: name=mysqld state=started enabled=yes


- name: ensure mysql started
  service: name=mysqld state=started enabled=yes

- name: my cnf file to root
  template: src=../templates/.my.cnf.j2 dest=/root owner=1000 mode=0600

- name: my cnf file to centos
  template: src=../templates/.my.cnf.j2 dest=/home/centos owner=centos group=centos mode=0600

- name: Copy mycnf file
  template: src=myCentos.cnf.j2 dest=/etc/my.cnf
  notify:
    - restart mysql

- name: Create a database
  mysql_db:
    name: demodb
    state: present


- name: Create a user
  mysql_user:
    name: jana
    password: "root"
    priv: '*.*:ALL'
    state: present
