---

- name: Install packages
  yum: name={{ item }} state=installed
  with_items:
    - MySQL-python
    - libselinux-python

- name: Install WGET
  yum: name=wget state=installed

- name: Download lib
  get_url: url=https://dev.mysql.com/get/mysql57-community-release-el7-9.noarch.rpm dest=/usr/mysql/mysql57-community-release-el7-9.noarch.rpm

- name: Install rpm
  yum: name=/usr/mysql/mysql57-community-release-el7-9.noarch.rpm state=present

- name: Install mySQL
  yum: name=mysql-server state=installed

- name: Copy mycnf file
  template: src=myCentos.cnf.j2 dest=/etc/my.cnf
  notify:
    - restart mysql

- name: Create directory /etc/mysql/conf.d
  file: path=/etc/mysql/conf.d state=directory
  notify:
    - restart mysql

- name: Deploy mysql config to conf.d
  template: src=mysql.cnf.j2 dest=/etc/mysql/conf.d/mysql.conf
  notify:
    - restart mysql

- name: Create directory /usr/mysql/
  file: path=/usr/mysql/ state=directory

- name: Start mysql service
  service: name=mysqld state=started enabled=yes
