---

- name: Install packages
  yum: name={{ item }} state=installed
  with_items:
    - mariadb-server
    - mariadb-devel
    - mariadb-libs
    - MySQL-python

#- name: Install mySQL
#  yum: name=mysql-server state=installed

- name: Copy mycnf file to mysql conf file
  template: src=.my.cnf.j2 dest=/etc/my.cnf owner=root group=root mode=0644
  notify: restart mysql

- name: Create datadir if it does not exist
  file:
    path: "{{ mysql_datadir }}"
    state: directory
    owner: mysql
    group: mysql
    mode:  0755
    setype: mysqld_db_t

- name: Ensure mysql started
  service: name=mariadb state=started enabled=yes

- name: Create a database
  mysql_db:
    name: demo
    state: present

- name: Create user
  mysql_user:
    name: jana
    password: jana123
    priv: '*.*:ALL,GRANT'
    state: present
    host: '%'
